### ISSUE TITLE
Wrong fusion result?

### ISSUE THREAD

**Issue by chinhodado** [Heimdall409/persona4-fusion-calculator#1]
For Persona 5:

For Abaddon: http://heimdall409.github.io/#/persona/Abaddon

One of the listed recipe is Kohryu (76 / Hierophant) + Seth (51 / Tower)

Now (76 + 51) / 2 = 63.5, round down to 63, add 1 -> 64. 

64 in Judgement is Yamata no Orochi, not Abaddon

**Comment by Ashyaa** [comment]
You are right.

There was a mistake in my average, it seems I forgot to round down the average before adding 1.
The average for this example was then 64.5, which led to listing this recipe for Abaddon instead of Yamata no Orochi.

Should be working fine now, thanks for the issue!
I'm closing this issue, open another one if you find any other inconsistencies!
