### ISSUE TITLE
Down rank fusion

### ISSUE THREAD

**Issue by chinhodado** [Heimdall409/persona4-fusion-calculator#2]
http://heimdall409.github.io/#/persona/Agathion

There should be Shiisaa (16 / Chariot)+Slime (10 / Chariot) in there.

Probably a bug with same-arcana downrank fusion.

**Comment by Ashyaa** [comment]
There was a missing condition when it was looking for the closest persona in the resulting arcana (both uprank and downrank): the resulting persona could be one the two persona used in fusion, which is obviously wrong and leading to false results.

It is now fixed for all types of fusion. Thanks again for this issue!

**Comment by chinhodado** [comment]
Not quite correct yet. Shiki-Ouji (21 / Chariot) + Slime (10 / Chariot) should also be in the list.

**Comment by Ashyaa** [comment]
I think I know why.

I've been unsure since the beginning about the average formula to use in the same arcana fusion case.
I didn't know if, in this case, I aldo had to do add 1 int he end, and in doubt I did so, which gives us:
Shiki-Ouji (21 / Chariot) + Slime (10 / Chariot) => [(21 + 10) / 2] + 1 = 16,5, rounded down to 16.
That would then give us Shiisaa (16 / Chariot). 

Without the final increment, the result is 15, which gives the game's result, Agathion (3 / Chariot).

My issue there is that I can't say that the rounded average, without an increment, is indeed the right formula. There could be, to 'mirror' the normal formula, a decrement (a minus one) at the end. It would still give us the same result in that specific case.

For now, I'll juste remove the increment, but I leave this issue open because there is some testing to be done. If, by chance, you have any further info on this problem, I'd be glad to take them into account to improve even more my results.

**Comment by chinhodado** [comment]
If the algorithm for same-arcana fusion is the same as in Persona 4, it is like this:
- Get `f(x1, x2) = floor(AVG(x1, x2)) + 1` where x1 and x2 are the two ingredients' ranks
- From there, go DOWN one rank in the arcana of the ingredients. This is different from normal 2-way fusion in which the result rank can be at least the result above.
- If the persona you got is the same as one of the ingredient, or cannot be fused (DLC you don't own, rare persona, special-formula persona) then continue to go down.

So for Shiki-Ouji + Slime, you got f(x1, x2) = 16, but you can't just take 16, you must go down one rank first, which is 15, then continue to go down until you reach Agathion.

The algorithm is taken from [here](https://web.archive.org/web/20131219130533/http://www.gamefaqs.com/ps2/945498-shin-megami-tensei-persona-4/faqs/54981) (search for section 006c3)

**Comment by Ashyaa** [comment]
This is the kind of info I needed back when I started this project.

Since it features Persona 4 and Persona 4 Golden, and since I'm almost sure the algorithm is the same for Persona 5, I'm gonna rewrite my same-arcana fusion algorithm to match this one. 

I'm not sure when I will be able to do it though, but be assured that I will do it as soon as possible.

**Comment by Ashyaa** [comment]
I had a bit of time this morning and wanted to be sure if the result of Shiki-Ouji (21 / Chariot) + Slime (10 / Chariot) was indeed Agathion (3 / Chariot) in game.

It turns out that Shiki-Ouji (21 / Chariot) + Slime (10 / Chariot) = Shiisaa (16 / Chariot);
![shiisaa fusion](https://cloud.githubusercontent.com/assets/7237493/19836081/d7489226-9e96-11e6-9123-66e8e9d7f197.jpg)

In the same fashion, Agathion (3 / Chariot) + Shiisaa (16 / Chariot) = Slime (10 / Chariot).
![slime fusion](https://cloud.githubusercontent.com/assets/7237493/19836084/0cba8d1a-9e97-11e6-8f14-66404e819258.jpg)

So it seems my first implementation was correct, Shiki-Ouji (21 / Chariot) + Slime (10 / Chariot) should not be in Agathion list. 

I'll still leave this issue open cause in need to test such cases in both Persona 4 and Persona 4 Golden to be really exhaustive.

**Comment by chinhodado** [comment]
You're right. I checked back on Persona 3 Portable and indeed it is "less than or equal" to `f(x1, x2) = floor(AVG(x1, x2)) + 1`, not a strict "less than".

For example here is Oumitsunu (30 / Chariot) + Koumokuten (43 / Chariot), which results in Nata Taishi (37 / Chariot):

![image](https://cloud.githubusercontent.com/assets/1388219/19838133/0a87e30a-9e9f-11e6-9a86-3786ac08bb23.png)

or Virtue (32 / Justice) + Throne (51 / Justice) = Dominion (42 / Justice):

![image](https://cloud.githubusercontent.com/assets/1388219/19838137/25dcf9f6-9e9f-11e6-8fb3-1da2e25fa7cd.png)

So the guide I linked and arantius's implementation are wrong.
